[package]
name = "bbf"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "bbf"
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror.workspace = true
xxhash-rust.workspace = true
zerocopy.workspace = true
